- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
  # 1
  - name: run the CL command to create a library
    ibmi_cl_command:
      cmd: crtlib lib(ansiblei)
    register: crt_lib_result

  # 2
  - name: print crtlib result
    debug:
      msg: 'crtlib result: {{ crt_lib_result }}'

  # 3
  - name: run the CL command to create the library again
    ibmi_cl_command:
      cmd: crtlib lib(ansiblei)
      joblog: true
    register: crt_lib_repeated_result
    ignore_errors: true

  # 4
  - name: print crtlib repeated result
    debug:
      msg: 'crtlib result: {{ crt_lib_repeated_result }}'

  # 5
  - name: assert the repeating creation of the library failed
    assert:
      that:
      - (crt_lib_repeated_result.job_log | selectattr('MESSAGE_ID', 'equalto', 'CPF2111') | map(attribute='MESSAGE_ID') | list | length) >= 1

  # 6
  - name: run the CL command to delete the library
    ibmi_cl_command:
      cmd: dltlib ansiblei
      joblog: false
