- hosts: ibmi
  gather_facts: false
  collections:
   - ibm.power_ibmi

  tasks:
  - name: run the CL command ANZDFTPWD to collect all the user profiles that have a default password
    ibmi_cl_command:
      cmd: ANZDFTPWD ACTION(*NONE)
      joblog: true

  - name: query the collected list of user profiles
    ibmi_sql_query:
      sql: "SELECT * FROM QUSRSYS.QASECPWD"
    register: default_password_user_list

  - name: display the collected list of user profiles
    debug:
      msg: "{{ default_password_user_list.row }}"
    when: setDisabled is defined and setDisabled | bool

  - name: debug setDisabled variable
    debug:
      msg: "setDisabled is {{ setDisabled | default('not defined') }}"

  - name: set the collected user profiles expired
    ibmi_cl_command:
      cmd: ANZDFTPWD ACTION(*PWDEXP)
      joblog: true
    when: setExpired is defined and setExpired | bool

  - name: set the collected user profiles disabled
    ibmi_cl_command:
      cmd: ANZDFTPWD ACTION(*DISABLE)
      joblog: true
    when: setDisabled is defined and setDisabled | bool

  - name: run the CL command to delete the report file
    ibmi_cl_command:
      cmd: CLRPFM FILE(QUSRSYS/QASECPWD) MBR(*ALL)
      joblog: false
