- hosts: ibmi
  gather_facts: no

  vars:
    checkout_dir: '/home/TEST/app'

  tasks:
    - name: run the CL command to create user
      ibm.power_ibmi.ibmi_cl_command:
        cmd: 'CRTUSRPRF USRPRF(TEST) PASSWORD(TEST1234)'
      register: crt_usr_result
      ignore_errors: True
    
    - name: run the CL command to create user home directory
      ibm.power_ibmi.ibmi_cl_command:
        cmd: 'CRTDIR "/home/TEST"'
      register: crt_usr_dir_result
      ignore_errors: True

    - name: verify git has been installed
      stat:
        path: /Qopensys/pkgs/bin/git
      register: git_stat

    - name: Install git if it's not there
      command: '/Qopensys/pkgs/bin/yum install git -y'
      when: git_stat.stat.exists == false
      ignore_errors: True

    - name: create symlink for git command to use git module
      command: ln -s /Qopensys/pkgs/bin/git /usr/bin/git
      ignore_errors: True
    
    - name: set http.sslVerify for git
      command: 'git config --global http.sslVerify false'
      ignore_errors: True

    - name: clone git repo
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.git:
        repo: https://github.com/yvesdebeer/ansible_demo.git
        dest: "{{ checkout_dir }}"

    - name: create patient library
      ibm.power_ibmi.ibmi_cl_command:
        cmd: 'CRTLIB LIB(PATIENT)'
      ignore_errors: True

    - name: run the CL command to ceate patient table
      ibm.power_ibmi.ibmi_cl_command:
        cmd: RUNSQLSTM SRCSTMF('/home/TEST/app/PatientInfoTable.sql') COMMIT(*NONE)
      register: crt_patient_result
      ignore_errors: True

    - name: query the patient info table
      ibm.power_ibmi.ibmi_sql_query:
        sql: "SELECT * FROM PATIENT.INFO"
      register: patient_info

    - name: display the collect list crt_patient_result
      debug:
        msg: "{{ patient_info.row }}"

